[package]
name = "youtube_downloader"
version = "0.1.0"
edition = "2026"

[dependencies]
eframe = "0.27"
egui = "0.27"
rfd = "0.14"
tokio = { version = "1", features = ["rt-multi-thread", "process", "io-util"] }

